default: &defaults
  push_api_key: "f9dc9fe7-ab7c-4d81-b6dd-dc6535a5261b"
  name: "Modular Sinatra test"
  debug: true

development:
  <<: *defaults
  active: true

production:
  <<: *defaults
  active: true
